version: 2.1

orbs:
  node: circleci/node@3.0.0
  gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.0.2

jobs:
  build:
    description: Install npm
    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
    machine: true
    steps:
      - checkout
      # Install node
      - node/install
      # Install npm
      - node/install-npm
      # Download and cache dependencies
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: npm install
          # Save cache
          cache-key: package.json
          # Ignore non-checksum cache hits
          use-strict-cache: true
  build_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      # - run: npm run test
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: circle-gke
          tag: "v2"
      - gcr/push-image:
          image: circle-gke
          tag: "v2"
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gke/install
      # Initialize the `gcloud` CLI.
      - gke/init
      # Update a deployment's Docker image.
      - gke/rollout-image:
          deployment: circle-ci-cluster
          container: dominic-backend
          image: gcr.io/circle-ci-demo-280609/circle-gke:v2
  deploy_new:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      # Install `gcloud` and `kubectl` if not already installed.
      - gke/install
      - gcr/gcr-auth
      # Updates the kubectl configuration file with GKE cluster access credentials
      - gke/update-kubeconfig-with-credentials:
          cluster: circle-ci-cluster
      # Update a deployment's Docker image.
      - gke/rollout-image:
          cluster: circle-ci-cluster
          container: dominic-backend
          deployment: circle-ci-cluster
          image: gcr.io/circle-ci-demo-280609/circle-gke 
          tag: v2

workflows:
  build_update_deploy:
    jobs:
      # - build_test
      # - Build-Push-Image-Docker:
      #     requires:
      #       - build_test
      - deploy_new
          # requires:
          #   - Build-Push-Image-Docker
      
